[package]
name = "dotto"
version = "0.1.2"
authors = ["babariviere <babathriviere@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
glob = "0.3"
md5 = "0.6"
path_abs = "0.4"
structopt = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
